### ISSUE TITLE
Split algorithm does not work as intended

### ISSUE THREAD

**Issue by kldtz** [dtuggener/CharSplit#4]
Thank you for sharing the code. Your compound splitter works very well, however, maybe not as intended. For each split position *n* instead of

```
score(n) = max p(prefix) + max p(suffix) − min p(infix),
```

what is actually computed by the code is

```
score(n) = p(word[:n]) + p(word[n:]) - min p(infix).
```
That is, the code iterates over all infix ngrams, but only uses the full prefix and suffix for the other two probabilities. I simplified the code to reflect this and removed some redundant steps: <https://github.com/kldtz/CharSplit>. Now the GermaNet evaluation runs in about half of the original time on my machine (yielding the same result).

I also tried using all prefix and suffix ngrams as described in the appendix of your thesis, but this has a negative effect on the performance for the GermaNet evaluation set.

**Comment by dtuggener** [comment]
You are correct, the current code doesn't replicate precisely what is described in the thesis appendix. What this modification does, is to look for the longest possible known (i.e. that are in the model) prefixes / suffixes and take the probabilities of these ngrams, rather than taking the max of all possible (known) ngrams. I noted that this boosts accuracy on GermaNet (beside speeding up the splitting process).

**Comment by kldtz** [comment]
Sorry for being pedantic: It's not the probability of the longest known prefix/suffix that is used, but always that of word[:n] and word[n:], as I described above. For unknown ngrams, you simply set a default of -1:

`ngram_probs["suffix"].get(end_ngram, -1)`
`ngram_probs["prefix"].get(ngram, -1)`

I simplified the code to make this more transparent (you can move the prefix and suffix blocks out of the inner loop since they can only be reached once, on the first iteration of the inner loop). It would be interesting to see whether the performance improves by taking the longest known suffixes/prefixes, though.

**Comment by kldtz** [comment]
Sorry for being pedantic: It's not the probability of the longest known prefix/suffix that is used, but always that of word[:n] and word[n:], as I described above. For unknown ngrams, you simply set a default of -1:

`ngram_probs["suffix"].get(end_ngram, -1)`
`ngram_probs["prefix"].get(ngram, -1)`

I simplified the code to make this more transparent (you can move the prefix and suffix blocks out of the inner loop since they can only be reached once, on the first iteration of the inner loop). It would be interesting to see whether the performance improves by taking the longest known suffixes/prefixes, though.

**Comment by dtuggener** [comment]
You're right,
https://github.com/dtuggener/CharSplit/blob/2ba640f81fb03ff771dacb0a99012e915846a782/charsplit/splitter.py#L52 will only trigger once, i.e. with `pre_slice` set to `word[:n]`.
Initially, the condition was `if k <= len(pre_slice)` (without `if not pre_slice_prob` which skips all other ngrams before `n`), as I wrote in the comment in the latest changes. 
The condition `if k <= len(pre_slice)` yields all ngrams up to `n` etc. As you wrote, this makes the codes slower, and it also gives lower accuracy in the Germanet evaluation (91% accuracy instead of 95%). However, it seems to give more meaningful scores to plausible split positions after the best one, i.e.:
```
(0.7945872450631273, 'Autobahn', 'Raststätte')
(0.7266789295399403, 'Auto', 'Bahnraststätte')
(0.2875569743289057, 'Autobahnrast', 'Stätte')
(-0.019170309025381527, 'Autobahnrasts', 'Tätte')
(-0.3766149094062159, 'Aut', 'Obahnraststätte')
(-0.5506006414454352, 'Autob', 'Ahnraststätte')
(-1.2333977717386229, 'Autobahnr', 'Aststätte')
(-1.4229782805317739, 'Autobahnras', 'Tstätte')
(-1.4726443768996962, 'Autobahnra', 'Ststätte')
(-1.6502353625641297, 'Autobah', 'Nraststätte')
(-1.802779961364542, 'Autobahnraststä', 'Tte')
(-1.8922764227642277, 'Autoba', 'Hnraststätte')
(-2.730248306997743, 'Autobahnrastst', 'Ätte')
```

instead of:
```
(0.7945872450631273, 'Autobahn', 'Raststätte')
(-0.7143290887876655, 'Auto', 'Bahnraststätte')
(-1.1132332878581173, 'Autobahnrast', 'Stätte')
(-1.4010051533086552, 'Aut', 'Obahnraststätte')
(-2.3447843979244944, 'Autobahnrasts', 'Tätte')
(-2.4761904761904763, 'Autobahnra', 'Ststätte')
(-2.4761904761904763, 'Autobahnr', 'Aststätte')
(-2.5733333333333333, 'Autob', 'Ahnraststätte')
(-2.604651162790698, 'Autobahnras', 'Tstätte')
(-2.7142857142857144, 'Autobah', 'Nraststätte')
(-2.730248306997743, 'Autobahnrastst', 'Ätte')
(-2.8033113109925973, 'Autobahnraststä', 'Tte')
(-3.0, 'Autoba', 'Hnraststätte')
```

Thinking back, I think this is why I stuck with only using `word[:n]`, but I didn't remove the (redundant) code for reproducibility.

**Comment by kldtz** [comment]
Thank you for your replies! I really like CharSplit. The idea is elegant and the splits I've seen it generate were very plausible, even for non-compounds, where it splits off affixes.

**Comment by kldtz** [comment]
One final comment (maybe interesting for people using the code): You can speed up the splitting process by removing some redundant iterations from the inner loop. I did this in the fork linked in the first comment (saves around 5 seconds for the GermaNet evaluation on my machine):
```
for k in range(len(word), n+2, -1):
    in_ngram = word[n:k]
    in_slice_prob.append(ngram_probs.infix.get(in_ngram, 1))
```
(Your code is selecting the infix with maximal length several times for each potential split position, which gives the same result but is slower.) That's what I was referring to above, but maybe it wasn't very clear.
